/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.65
 * Generated at: 2022-12-11 19:19:57 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.project;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/project/include/jQueryMobile.inc", Long.valueOf(1670604375000L));
    _jspx_dependants.put("/project/include/info.inc", Long.valueOf(1670604746000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE HTML>\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<title>추천 게임</title>\r\n");
      out.write("<link rel=\"apple-touch-icon\" sizes=\"57x57\" href=\"include/icon/apple-icon-57x57.png\">\r\n");
      out.write("<link rel=\"apple-touch-icon\" sizes=\"60x60\" href=\"include/icon/apple-icon-60x60.png\">\r\n");
      out.write("<link rel=\"apple-touch-icon\" sizes=\"72x72\" href=\"include/icon/apple-icon-72x72.png\">\r\n");
      out.write("<link rel=\"apple-touch-icon\" sizes=\"76x76\" href=\"include/icon/apple-icon-76x76.png\">\r\n");
      out.write("<link rel=\"apple-touch-icon\" sizes=\"114x114\" href=\"include/icon/apple-icon-114x114.png\">\r\n");
      out.write("<link rel=\"apple-touch-icon\" sizes=\"120x120\" href=\"include/icon/apple-icon-120x120.png\">\r\n");
      out.write("<link rel=\"apple-touch-icon\" sizes=\"144x144\" href=\"include/icon/apple-icon-144x144.png\">\r\n");
      out.write("<link rel=\"apple-touch-icon\" sizes=\"152x152\" href=\"include/icon/apple-icon-152x152.png\">\r\n");
      out.write("<link rel=\"apple-touch-icon\" sizes=\"180x180\" href=\"include/icon/apple-icon-180x180.png\">\r\n");
      out.write("<link rel=\"icon\" type=\"image/png\" sizes=\"192x192\"  href=\"include/icon/android-icon-192x192.png\">\r\n");
      out.write("<link rel=\"icon\" type=\"image/png\" sizes=\"32x32\" href=\"include/icon/favicon-32x32.png\">\r\n");
      out.write("<link rel=\"icon\" type=\"image/png\" sizes=\"96x96\" href=\"include/icon/favicon-96x96.png\">\r\n");
      out.write("<link rel=\"icon\" type=\"image/png\" sizes=\"16x16\" href=\"include/icon/favicon-16x16.png\">\r\n");
      out.write("<link rel=\"manifest\" href=\"include/icon/manifest.json\">\r\n");
      out.write("<meta name=\"msapplication-TileColor\" content=\"#ffffff\">\r\n");
      out.write("<meta name=\"msapplication-TileImage\" content=\"include/icon/ms-icon-144x144.png\">\r\n");
      out.write("<meta name=\"theme-color\" content=\"#ffffff\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<!-- jQuery, jQuery Mobile ë¼ì´ë¸ë¬ë¦¬ ì¬ì©: CDN ë°©ì --> \n");
      out.write("<link rel=\"stylesheet\" href=\"http://code.jquery.com/mobile/1.0.1/jquery.mobile-1.0.1.min.css\" />\n");
      out.write("<script src=\"http://code.jquery.com/jquery-1.6.4.min.js\"></script>\n");
      out.write("<script src=\"http://code.jquery.com/mobile/1.0.1/jquery.mobile-1.0.1.min.js\"></script>\n");
      out.write("<!--\n");
      out.write("<link rel=\"stylesheet\" href=\"http://code.jquery.com/mobile/1.3.1/jquery.mobile-1.3.1.min.css\" />\n");
      out.write("<script src=\"http://code.jquery.com/jquery-1.9.1.min.js\"></script>\n");
      out.write("<script src=\"http://code.jquery.com/mobile/1.3.1/jquery.mobile-1.3.1.min.js\"></script>\n");
      out.write("-->");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("document.cookie = \"safeCookie1=foo; SameSite=Lax\"; \r\n");
      out.write("document.cookie = \"safeCookie2=foo\";  \r\n");
      out.write("document.cookie = \"crossCookie=bar; SameSite=None; Secure\";\r\n");
      out.write("\r\n");
      out.write("// 웹문서 로딩이 완료된 후에 실행할 함수 정의 \r\n");
      out.write("$(function() {\r\n");
      out.write("     // HTML DOM Tree 구조에 따라 <ul>, <li>, <a> 엘리먼트가 클릭되면 실행될 함수 정의\r\n");
      out.write("	$('ul li a').click(function() {\r\n");
      out.write("	    	    ///// page1 /////\r\n");
      out.write("	    // 클릭된 개체(this) 내의 각 엘리먼트를 찾아(find), 그 속성(attr) 또는 데이터(text) 인식\r\n");
      out.write("		var imageSrc   = $(this).find('img').attr('src');\r\n");
      out.write("		var imageTitle = $(this).find('h3').text();	\r\n");
      out.write("		var imageDesc  = $(this).find('p').text();\r\n");
      out.write("		var videoSrc   = $(this).find('div').text();	\r\n");
      out.write("		var detail     = $(this).find('section').text();\r\n");
      out.write("		\r\n");
      out.write("		var audioSrc   = $(this).find('article').text();	\r\n");
      out.write("\r\n");
      out.write("		///// page2 /////\r\n");
      out.write("		// id를 이용한 개체 인식 및 값 할당\r\n");
      out.write("		// 이미지 소스 변경\r\n");
      out.write("		$(\"#p2_image\").attr('src', imageSrc);	\r\n");
      out.write("		// 개체에 HTML 문자로 쓰기\r\n");
      out.write("		$(\"#p2_title\").html(imageTitle);	\r\n");
      out.write("		$(\"#p2_desc\").html(imageDesc);	\r\n");
      out.write("		$(\"#p2_detail\").html(detail);	\r\n");
      out.write("		$(\"#p2_audio\").attr('href', audioSrc);\r\n");
      out.write("\r\n");
      out.write("		var video = $(\"#p2_video\");\r\n");
      out.write("		video.attr('src', \"video/\" + videoSrc);\r\n");
      out.write("		video.get(0).play();\r\n");
      out.write("	});\r\n");
      out.write("});\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<!-- 첫 번째 페이지: 시작 -->\r\n");
      out.write("<section data-role=\"page\" id=\"page1\">\r\n");
      out.write("\r\n");
      out.write("	<!-- 1. 헤더 -->\r\n");
      out.write("	<header data-role=\"header\" data-theme=\"b\">\r\n");
      out.write("		<!-- 헤더 타이틀 -->\r\n");
      out.write("		<h1>게임 목록</h1>\r\n");
      out.write("	</header> \r\n");
      out.write("\r\n");
      out.write("	<!-- 2. 본문 -->\r\n");
      out.write("	<section data-role=\"content\"> \r\n");
      out.write("	\r\n");
      out.write("		");

		String[] title       = {"메이플스토리", "던전앤파이터", "서든어택", "피파온라인4", "리그오브레전드"};
		String[] image_name  = {"maple.jpeg", "fighter.jpeg", "sudden.jpeg", "fifa4.jpeg", "legend.jpeg"};
		String[] description = {"MMORPG | PC", "벨트 스크롤 액션 RPG | PC", "FPS | PC", "스포츠 | PC", "MOBA  | PC"};
		String[] video_name  = {"maple.mp4", "fighter.mp4", "sudden.mp4", "fifa4.mp4", "legend.mp4"};
		String[] detail      = {"SD 생김새의 캐릭터가 모험을 떠나면서 성장하는 2D 횡스크롤 게임이다.", "'빠른 플레이'라는 문구에 딱 들어맞는 게임으로, 별다른 생각없이 가볍게 한판 놀 수 있는 오락실 아케이드 게임의 온라인 버전이다.","박진감 넘치고, 빠른 게임성으로 유저들이 쉽게 적응할 수 있고, 다양한 모드를 통해 FPS 게임을 좋아하지 않은 유저들도 쉽게 접근 할 수 있는 게임입니다.", "전 세계 축구 리그의 선수들로 플레이 할 수 있는 최고의 온라인 축구 게임 입니다.","라이엇 게임즈에서 개발 및 서비스하는 멀티플레이어 온라인 배틀 아레나 비디오 게임이다."};
		String[] game_audio  = {"audio/maple_audio.jsp" ,"audio/fighter_audio.jsp" ,"audio/sudden_audio.jsp" ,"audio/fifa4_audio.jsp" ,"audio/legend_audio.jsp"};
		
      out.write("\r\n");
      out.write("	    <!-- 목록 -->\r\n");
      out.write("		<ul data-role=\"listview\" data-inset=\"true\" data-theme=\"e\"> \r\n");
      out.write("\r\n");
      out.write("		    ");

			for (int i=0; i<title.length; i++) { 
			
      out.write("\r\n");
      out.write("				<!-- 목록 아이템 -->\r\n");
      out.write("				<li>\r\n");
      out.write("					<a href=\"#page2\" data-rel=\"dialog\" data-transition=\"pop\">\r\n");
      out.write("						<!-- 이미지 : 소스,제목,설명 -->\r\n");
      out.write("						<img src=\"image/");
      out.print( image_name[i] );
      out.write("\" width=100% height=100%>\r\n");
      out.write("						<h3>");
      out.print( title[i] );
      out.write("</h3>\r\n");
      out.write("						<p>");
      out.print( description[i] );
      out.write("</p>\r\n");
      out.write("						<div style=\"display: none\">");
      out.print( video_name[i] );
      out.write("</div>\r\n");
      out.write("						<section style=\"display: none\">");
      out.print( detail[i] );
      out.write("</section>\r\n");
      out.write("						<article style=\"display: none\">");
      out.print( game_audio[i] );
      out.write("</article>\r\n");
      out.write("					</a>\r\n");
      out.write("				</li>				\r\n");
      out.write("		    ");

			}  
			
      out.write("\r\n");
      out.write("			\r\n");
      out.write("		</ul>	\r\n");
      out.write("\r\n");
      out.write("	</section> \r\n");
      out.write("\r\n");
      out.write("	<!-- 3. 푸터 -->\r\n");
      out.write("	<footer data-role=\"footer\" data-theme=\"c\" data-position=\"fixed\">\r\n");
      out.write("        ");
      out.write("\n");
      out.write("<h3>(주)Game World 서울 중랑구 묵동 1234</h3>");
      out.write("\r\n");
      out.write("	</footer>\r\n");
      out.write("\r\n");
      out.write("</section>\r\n");
      out.write("<!-- 첫 번째 페이지: 끝 -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- 두 번쩨 페이지: 시작 -->\r\n");
      out.write("<section data-role=\"page\" id=\"page2\">\r\n");
      out.write("\r\n");
      out.write("	<!-- 1. 헤더 -->\r\n");
      out.write("	<header data-role=\"header\" data-theme=\"a\">\r\n");
      out.write("		<!-- 헤더 타이틀 -->\r\n");
      out.write("		<h1 id=\"p2_title\"></h1>\r\n");
      out.write("	</header> \r\n");
      out.write("\r\n");
      out.write("	<!-- 2. 본문 -->\r\n");
      out.write("	<section data-role=\"content\"> \r\n");
      out.write("        <!-- 이미지 소스 --> \r\n");
      out.write("		<img id=\"p2_image\" width=\"100%\">\r\n");
      out.write("		\r\n");
      out.write("		<!-- 이미지 설명-->\r\n");
      out.write("		<p id=\"p2_desc\"></p> \r\n");
      out.write("		<video id=\"p2_video\" width= \"100%\" preload=\"false\" controls=\"controls\"></video>\r\n");
      out.write("		<h1 id=\"p2_title\"> 플레이 영상</h1>\r\n");
      out.write("		<p id=\"p2_detail\"></p>\r\n");
      out.write("\r\n");
      out.write("		<a target=\"_blank\" id=\"p2_audio\">추억의 게임 BGM 듣기</a>\r\n");
      out.write("\r\n");
      out.write("	</section> \r\n");
      out.write("\r\n");
      out.write("</section> \r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
